import {
  Activity,
  BarChart3,
  Building2,
  CalendarDays,
  CalendarRange,
  Car,
  ClipboardList,
  Database,
  FileText,
  Gauge,
  HandHelping,
  LayoutDashboard,
  type LucideIcon,
  Map,
  PhoneCall,
  Radio,
  ScrollText,
  Settings,
  ShieldAlert,
  Target,
  Users,
  UserCog,
  Wrench,
} from "lucide-react";

/**
 * Registro único dos 20 módulos do SIG-GCMI.
 * Alimenta o menu lateral, as rotas, as tabelas e os formulários genéricos
 * (`components/data-module.tsx`) — as mesmas chaves usadas nas permissões da API.
 */

export type Secao = "Operacional" | "Administrativo" | "Relatórios" | "Sistema";

export type TipoCampo =
  | "texto"
  | "textarea"
  | "numero"
  | "data"
  | "datahora"
  | "hora"
  | "select"
  | "cor"
  | "relacao";

export type Relacao = "efetivo" | "viaturas" | "orgaos";

export interface CampoDef {
  campo: string;
  rotulo: string;
  tipo: TipoCampo;
  opcoes?: string[];
  relacao?: Relacao;
  obrigatorio?: boolean;
  largura?: "meia" | "cheia";
  dica?: string;
}

export interface ColunaDef {
  campo: string;
  rotulo: string;
  tipo?: "texto" | "data" | "datahora" | "status" | "numero" | "relacao";
  relacao?: Relacao;
}

export interface ModuloDef {
  /** Chave de permissão (igual à da API). */
  chave: string;
  /** Nome do procedimento oRPC do CRUD (quando houver). */
  rpc?: string;
  rota: string;
  titulo: string;
  curto: string;
  descricao: string;
  icone: LucideIcon;
  secao: Secao;
  /** Página própria (dashboard, mapa, etc.) em vez do CRUD genérico. */
  propria?: boolean;
  singular?: string;
  colunas?: ColunaDef[];
  campos?: CampoDef[];
  filtros?: string[];
  ordenarPor?: string;
}

const SIM_NAO = ["Sim", "Não"];

export const OPCOES = {
  situacaoAtendimento: ["Aberta", "Em andamento", "Finalizada", "Perdida"],
  tipoAtendimento: ["Ocorrência", "Informação", "Solicitação", "Denúncia", "Trote"],
  canal: ["153", "Telefone", "Presencial", "WhatsApp", "Rádio", "Ofício", "Outro"],
  tipoOcorrencia: [
    "Perturbação do sossego",
    "Violência doméstica",
    "Dano ao patrimônio público",
    "Trânsito",
    "Furto",
    "Roubo",
    "Uso de drogas",
    "Desordem em via pública",
    "Maus-tratos a animais",
    "Ambiental",
    "Apoio a órgão público",
    "Outros",
  ],
  prioridade: ["Baixa", "Média", "Alta", "Crítica"],
  statusOcorrencia: ["Aberta", "Em andamento", "Encerrada", "Suspeita"],
  tipoAtividade: ["Patrulhamento", "Fiscalização", "Investigação", "Intervenção", "Prevenção"],
  statusAtividade: ["Planejada", "Em execução", "Concluída", "Cancelada"],
  tipoApoio: ["Evento público", "Manifestação", "Festa", "Show", "Escolar", "Religioso", "Outro"],
  statusApoio: ["Solicitado", "Aprovado", "Em execução", "Concluído", "Negado"],
  categoriaEvento: [
    "Treinamento",
    "Reunião",
    "Evento público",
    "Data comemorativa",
    "Folga institucional",
    "Institucional",
  ],
  statusEvento: ["Confirmado", "Previsto", "Cancelado", "Realizado"],
  tipoOperacao: ["Ordinária", "Especial", "Integrada", "Preventiva", "Emergencial"],
  statusOperacao: ["Planejada", "Em andamento", "Encerrada", "Cancelada"],
  turnoRonda: ["Manhã", "Tarde", "Noite", "Extra"],
  statusRonda: ["Planejada", "Em execução", "Concluída", "Interrompida"],
  tipoZona: ["Zona", "Distrito", "Setor", "Área de risco"],
  cargo: ["Comandante", "Subcomandante", "Inspetor", "Subinspetor", "Agente"],
  setor: ["Operacional", "Administrativo", "Trânsito", "Escolar", "Ambiental", "Inteligência"],
  statusAgente: ["Ativo", "Férias", "Licença", "Afastado", "Inativo"],
  turnoEscala: [
    "Manhã (07h-13h)",
    "Tarde (13h-19h)",
    "Noite (19h-01h)",
    "Madrugada (01h-07h)",
    "12x36 diurno",
    "12x36 noturno",
  ],
  tipoEscala: ["Normal", "Extra", "Repouso", "Férias", "Licença"],
  statusEscala: ["Prevista", "Confirmada", "Cumprida", "Falta"],
  tipoViatura: ["Automóvel", "Motocicleta", "Caminhonete", "Van", "Bicicleta"],
  statusViatura: ["Operacional", "Manutenção", "Indisponível", "Desativada"],
  tipoManutencao: ["Preventiva", "Corretiva", "Sinistro", "Revisão"],
  statusManutencao: ["Agendada", "Em execução", "Concluída"],
  tipoOrgao: [
    "Polícia Militar",
    "Polícia Civil",
    "Bombeiros",
    "SAMU",
    "Saúde",
    "Assistência Social",
    "Prefeitura",
    "Ministério Público",
    "Conselho Tutelar",
    "Outros",
  ],
  tipoRelatorio: ["Ocorrências", "Atendimentos", "Atividades", "Efetivo", "Viaturas", "Rondas", "Consolidado"],
  periodicidade: ["Diário", "Semanal", "Mensal", "Anual", "Ad-hoc"],
  formato: ["CSV", "PDF", "Excel"],
  categoriaIndicador: ["Operacional", "Administrativo", "Efetivo", "Frota", "Atendimento", "Gestão"],
  sentido: ["Maior é melhor", "Menor é melhor"],
  ativo: ["Ativo", "Inativo"],
  simNao: SIM_NAO,
};

export const MODULOS: ModuloDef[] = [
  /* -------------------------------------------------------------- OPERACIONAL */
  {
    chave: "dashboard",
    rota: "/central/dashboard",
    titulo: "Dashboard Operacional",
    curto: "Dashboard",
    descricao: "Visão geral em tempo real da atividade da Guarda.",
    icone: LayoutDashboard,
    secao: "Operacional",
    propria: true,
  },
  {
    chave: "atendimentos",
    rota: "/central/atendimentos",
    titulo: "Central de Atendimento 153",
    curto: "Atendimentos 153",
    singular: "atendimento",
    descricao: "Registro das chamadas recebidas pela central.",
    icone: PhoneCall,
    secao: "Operacional",
    ordenarPor: "dataHora",
    filtros: ["situacao", "tipo"],
    colunas: [
      { campo: "protocolo", rotulo: "Protocolo" },
      { campo: "dataHora", rotulo: "Data/Hora", tipo: "datahora" },
      { campo: "tipo", rotulo: "Tipo" },
      { campo: "canal", rotulo: "Canal" },
      { campo: "solicitanteNome", rotulo: "Solicitante" },
      { campo: "bairro", rotulo: "Bairro" },
      { campo: "situacao", rotulo: "Situação", tipo: "status" },
    ],
    campos: [
      { campo: "protocolo", rotulo: "Protocolo", tipo: "texto", dica: "Gerado automaticamente se vazio" },
      { campo: "dataHora", rotulo: "Data e hora", tipo: "datahora" },
      { campo: "tipo", rotulo: "Tipo", tipo: "select", opcoes: OPCOES.tipoAtendimento, obrigatorio: true },
      { campo: "canal", rotulo: "Canal", tipo: "select", opcoes: OPCOES.canal },
      { campo: "situacao", rotulo: "Situação", tipo: "select", opcoes: OPCOES.situacaoAtendimento, obrigatorio: true },
      { campo: "duracaoSegundos", rotulo: "Duração (segundos)", tipo: "numero" },
      { campo: "solicitanteNome", rotulo: "Nome do solicitante", tipo: "texto" },
      { campo: "solicitanteTelefone", rotulo: "Telefone", tipo: "texto" },
      { campo: "endereco", rotulo: "Endereço", tipo: "texto", largura: "cheia" },
      { campo: "bairro", rotulo: "Bairro/Localidade", tipo: "texto" },
      { campo: "atendenteId", rotulo: "Atendente", tipo: "relacao", relacao: "efetivo" },
      { campo: "descricao", rotulo: "Descrição do chamado", tipo: "textarea", largura: "cheia" },
      { campo: "acoes", rotulo: "Ações tomadas", tipo: "textarea", largura: "cheia" },
    ],
  },
  {
    chave: "ocorrencias",
    rota: "/central/ocorrencias",
    titulo: "Registro de Ocorrências",
    curto: "Ocorrências",
    singular: "ocorrência",
    descricao: "Boletins de ocorrência atendidos pela Guarda Municipal.",
    icone: ShieldAlert,
    secao: "Operacional",
    ordenarPor: "dataHora",
    filtros: ["status", "prioridade", "tipo"],
    colunas: [
      { campo: "numero", rotulo: "Número" },
      { campo: "dataHora", rotulo: "Data/Hora", tipo: "datahora" },
      { campo: "tipo", rotulo: "Tipo" },
      { campo: "bairro", rotulo: "Bairro" },
      { campo: "prioridade", rotulo: "Prioridade", tipo: "status" },
      { campo: "status", rotulo: "Status", tipo: "status" },
      { campo: "responsavelId", rotulo: "Responsável", tipo: "relacao", relacao: "efetivo" },
    ],
    campos: [
      { campo: "numero", rotulo: "Número", tipo: "texto", dica: "Gerado automaticamente se vazio" },
      { campo: "dataHora", rotulo: "Data e hora", tipo: "datahora" },
      { campo: "tipo", rotulo: "Tipo", tipo: "select", opcoes: OPCOES.tipoOcorrencia, obrigatorio: true },
      { campo: "natureza", rotulo: "Natureza", tipo: "texto" },
      { campo: "prioridade", rotulo: "Prioridade", tipo: "select", opcoes: OPCOES.prioridade, obrigatorio: true },
      { campo: "status", rotulo: "Status", tipo: "select", opcoes: OPCOES.statusOcorrencia, obrigatorio: true },
      { campo: "endereco", rotulo: "Endereço", tipo: "texto", largura: "cheia" },
      { campo: "bairro", rotulo: "Bairro/Localidade", tipo: "texto" },
      { campo: "zona", rotulo: "Zona", tipo: "texto" },
      { campo: "latitude", rotulo: "Latitude", tipo: "numero", dica: "Ex.: -6.7899" },
      { campo: "longitude", rotulo: "Longitude", tipo: "numero", dica: "Ex.: -38.7159" },
      { campo: "denunciante", rotulo: "Denunciante", tipo: "texto" },
      { campo: "denuncianteTelefone", rotulo: "Telefone do denunciante", tipo: "texto" },
      { campo: "vitima", rotulo: "Vítima", tipo: "texto" },
      { campo: "envolvidos", rotulo: "Envolvidos", tipo: "textarea", largura: "cheia" },
      { campo: "responsavelId", rotulo: "Agente responsável", tipo: "relacao", relacao: "efetivo" },
      { campo: "viaturaId", rotulo: "Viatura", tipo: "relacao", relacao: "viaturas" },
      { campo: "descricao", rotulo: "Descrição dos fatos", tipo: "textarea", largura: "cheia" },
      { campo: "providencias", rotulo: "Providências adotadas", tipo: "textarea", largura: "cheia" },
      { campo: "observacoes", rotulo: "Observações", tipo: "textarea", largura: "cheia" },
      { campo: "encerradoEm", rotulo: "Encerrada em", tipo: "datahora" },
    ],
  },
  {
    chave: "atividades",
    rota: "/central/atividades",
    titulo: "Atividades Operacionais",
    curto: "Atividades",
    singular: "atividade",
    descricao: "Planejamento e acompanhamento das atividades da corporação.",
    icone: ClipboardList,
    secao: "Operacional",
    ordenarPor: "inicioPrevisto",
    filtros: ["status", "tipo", "prioridade"],
    colunas: [
      { campo: "codigo", rotulo: "Código" },
      { campo: "titulo", rotulo: "Título" },
      { campo: "tipo", rotulo: "Tipo" },
      { campo: "inicioPrevisto", rotulo: "Início previsto", tipo: "datahora" },
      { campo: "local", rotulo: "Local" },
      { campo: "progresso", rotulo: "Progresso %", tipo: "numero" },
      { campo: "status", rotulo: "Status", tipo: "status" },
    ],
    campos: [
      { campo: "titulo", rotulo: "Título", tipo: "texto", obrigatorio: true, largura: "cheia" },
      { campo: "codigo", rotulo: "Código", tipo: "texto" },
      { campo: "tipo", rotulo: "Tipo", tipo: "select", opcoes: OPCOES.tipoAtividade, obrigatorio: true },
      { campo: "prioridade", rotulo: "Prioridade", tipo: "select", opcoes: OPCOES.prioridade, obrigatorio: true },
      { campo: "status", rotulo: "Status", tipo: "select", opcoes: OPCOES.statusAtividade, obrigatorio: true },
      { campo: "inicioPrevisto", rotulo: "Início previsto", tipo: "datahora" },
      { campo: "fimPrevisto", rotulo: "Fim previsto", tipo: "datahora" },
      { campo: "local", rotulo: "Local", tipo: "texto" },
      { campo: "equipe", rotulo: "Equipe", tipo: "texto" },
      { campo: "responsavelId", rotulo: "Responsável", tipo: "relacao", relacao: "efetivo" },
      { campo: "viaturaId", rotulo: "Viatura", tipo: "relacao", relacao: "viaturas" },
      { campo: "progresso", rotulo: "Progresso (%)", tipo: "numero" },
      { campo: "descricao", rotulo: "Descrição", tipo: "textarea", largura: "cheia" },
      { campo: "resultado", rotulo: "Resultado", tipo: "textarea", largura: "cheia" },
    ],
  },
  {
    chave: "apoios",
    rota: "/central/apoios",
    titulo: "Apoios e Atividades Institucionais",
    curto: "Apoios",
    singular: "apoio",
    descricao: "Apoios a eventos e demandas de outros órgãos.",
    icone: HandHelping,
    secao: "Operacional",
    ordenarPor: "dataHora",
    filtros: ["status", "tipo"],
    colunas: [
      { campo: "nomeEvento", rotulo: "Evento" },
      { campo: "tipo", rotulo: "Tipo" },
      { campo: "dataHora", rotulo: "Data/Hora", tipo: "datahora" },
      { campo: "local", rotulo: "Local" },
      { campo: "publicoEstimado", rotulo: "Público", tipo: "numero" },
      { campo: "efetivoNecessario", rotulo: "Efetivo", tipo: "numero" },
      { campo: "status", rotulo: "Status", tipo: "status" },
    ],
    campos: [
      { campo: "nomeEvento", rotulo: "Nome do evento", tipo: "texto", obrigatorio: true, largura: "cheia" },
      { campo: "tipo", rotulo: "Tipo", tipo: "select", opcoes: OPCOES.tipoApoio, obrigatorio: true },
      { campo: "status", rotulo: "Status", tipo: "select", opcoes: OPCOES.statusApoio, obrigatorio: true },
      { campo: "dataHora", rotulo: "Início", tipo: "datahora" },
      { campo: "dataFim", rotulo: "Término", tipo: "datahora" },
      { campo: "local", rotulo: "Local", tipo: "texto" },
      { campo: "solicitante", rotulo: "Solicitante", tipo: "texto" },
      { campo: "orgaoId", rotulo: "Órgão solicitante", tipo: "relacao", relacao: "orgaos" },
      { campo: "publicoEstimado", rotulo: "Público estimado", tipo: "numero" },
      { campo: "efetivoNecessario", rotulo: "Efetivo necessário", tipo: "numero" },
      { campo: "equipes", rotulo: "Equipes designadas", tipo: "texto" },
      { campo: "viaturas", rotulo: "Viaturas empregadas", tipo: "texto" },
      { campo: "briefing", rotulo: "Briefing", tipo: "textarea", largura: "cheia" },
      { campo: "relatorioPos", rotulo: "Relatório pós-evento", tipo: "textarea", largura: "cheia" },
      { campo: "observacoes", rotulo: "Observações", tipo: "textarea", largura: "cheia" },
    ],
  },
  {
    chave: "eventos",
    rota: "/central/eventos",
    titulo: "Agenda de Eventos",
    curto: "Eventos",
    singular: "evento",
    descricao: "Calendário institucional: treinamentos, reuniões e datas.",
    icone: CalendarDays,
    secao: "Operacional",
    ordenarPor: "inicio",
    filtros: ["status", "categoria"],
    colunas: [
      { campo: "titulo", rotulo: "Título" },
      { campo: "categoria", rotulo: "Categoria" },
      { campo: "inicio", rotulo: "Início", tipo: "datahora" },
      { campo: "fim", rotulo: "Fim", tipo: "datahora" },
      { campo: "local", rotulo: "Local" },
      { campo: "responsavel", rotulo: "Responsável" },
      { campo: "status", rotulo: "Status", tipo: "status" },
    ],
    campos: [
      { campo: "titulo", rotulo: "Título", tipo: "texto", obrigatorio: true, largura: "cheia" },
      { campo: "categoria", rotulo: "Categoria", tipo: "select", opcoes: OPCOES.categoriaEvento, obrigatorio: true },
      { campo: "status", rotulo: "Status", tipo: "select", opcoes: OPCOES.statusEvento, obrigatorio: true },
      { campo: "inicio", rotulo: "Início", tipo: "datahora", obrigatorio: true },
      { campo: "fim", rotulo: "Fim", tipo: "datahora" },
      { campo: "local", rotulo: "Local", tipo: "texto" },
      { campo: "responsavel", rotulo: "Responsável", tipo: "texto" },
      { campo: "publicoAlvo", rotulo: "Público-alvo", tipo: "texto" },
      { campo: "descricao", rotulo: "Descrição", tipo: "textarea", largura: "cheia" },
    ],
  },
  {
    chave: "operacoes",
    rota: "/central/operacoes",
    titulo: "Operações",
    curto: "Operações",
    singular: "operação",
    descricao: "Operações ordinárias, especiais e integradas.",
    icone: Target,
    secao: "Operacional",
    ordenarPor: "inicio",
    filtros: ["status", "tipo"],
    colunas: [
      { campo: "nome", rotulo: "Operação" },
      { campo: "tipo", rotulo: "Tipo" },
      { campo: "inicio", rotulo: "Início", tipo: "datahora" },
      { campo: "fim", rotulo: "Fim", tipo: "datahora" },
      { campo: "comandante", rotulo: "Comandante" },
      { campo: "efetivoEmpregado", rotulo: "Efetivo", tipo: "numero" },
      { campo: "status", rotulo: "Status", tipo: "status" },
    ],
    campos: [
      { campo: "nome", rotulo: "Nome da operação", tipo: "texto", obrigatorio: true, largura: "cheia" },
      { campo: "tipo", rotulo: "Tipo", tipo: "select", opcoes: OPCOES.tipoOperacao, obrigatorio: true },
      { campo: "status", rotulo: "Status", tipo: "select", opcoes: OPCOES.statusOperacao, obrigatorio: true },
      { campo: "inicio", rotulo: "Início", tipo: "datahora" },
      { campo: "fim", rotulo: "Fim", tipo: "datahora" },
      { campo: "comandante", rotulo: "Comandante", tipo: "texto" },
      { campo: "efetivoEmpregado", rotulo: "Efetivo empregado", tipo: "numero" },
      { campo: "viaturasEmpregadas", rotulo: "Viaturas empregadas", tipo: "numero" },
      { campo: "orgaosApoio", rotulo: "Órgãos de apoio", tipo: "texto", largura: "cheia" },
      { campo: "areaAtuacao", rotulo: "Área de atuação", tipo: "texto", largura: "cheia" },
      { campo: "objetivo", rotulo: "Objetivo", tipo: "textarea", largura: "cheia" },
      { campo: "resultado", rotulo: "Resultado", tipo: "textarea", largura: "cheia" },
    ],
  },
  {
    chave: "rondas",
    rota: "/central/rondas",
    titulo: "Controle de Rondas",
    curto: "Rondas",
    singular: "ronda",
    descricao: "Rondas realizadas por turno, equipe e localidade.",
    icone: Radio,
    secao: "Operacional",
    ordenarPor: "data",
    filtros: ["status", "turno"],
    colunas: [
      { campo: "data", rotulo: "Data", tipo: "data" },
      { campo: "turno", rotulo: "Turno" },
      { campo: "horaInicio", rotulo: "Início" },
      { campo: "horaFim", rotulo: "Fim" },
      { campo: "localidade", rotulo: "Localidade" },
      { campo: "agenteId", rotulo: "Agente", tipo: "relacao", relacao: "efetivo" },
      { campo: "viaturaId", rotulo: "Viatura", tipo: "relacao", relacao: "viaturas" },
      { campo: "status", rotulo: "Status", tipo: "status" },
    ],
    campos: [
      { campo: "data", rotulo: "Data", tipo: "data", obrigatorio: true },
      { campo: "turno", rotulo: "Turno", tipo: "select", opcoes: OPCOES.turnoRonda, obrigatorio: true },
      { campo: "horaInicio", rotulo: "Hora de início", tipo: "hora" },
      { campo: "horaFim", rotulo: "Hora de término", tipo: "hora" },
      { campo: "status", rotulo: "Status", tipo: "select", opcoes: OPCOES.statusRonda, obrigatorio: true },
      { campo: "agenteId", rotulo: "Agente responsável", tipo: "relacao", relacao: "efetivo" },
      { campo: "viaturaId", rotulo: "Viatura", tipo: "relacao", relacao: "viaturas" },
      { campo: "equipe", rotulo: "Equipe", tipo: "texto" },
      { campo: "localidade", rotulo: "Localidade", tipo: "texto" },
      { campo: "kmInicial", rotulo: "KM inicial", tipo: "numero" },
      { campo: "kmFinal", rotulo: "KM final", tipo: "numero" },
      { campo: "roteiro", rotulo: "Roteiro", tipo: "textarea", largura: "cheia" },
      { campo: "pontosVerificacao", rotulo: "Pontos de verificação", tipo: "textarea", largura: "cheia" },
      { campo: "incidentes", rotulo: "Incidentes", tipo: "textarea", largura: "cheia" },
      { campo: "observacoes", rotulo: "Observações", tipo: "textarea", largura: "cheia" },
    ],
  },
  {
    chave: "mapa",
    rpc: "zonas",
    rota: "/central/mapa",
    titulo: "Mapa Operacional",
    curto: "Mapa",
    singular: "zona",
    descricao: "Georreferenciamento de ocorrências, viaturas e zonas.",
    icone: Map,
    secao: "Operacional",
    propria: true,
    ordenarPor: "nome",
    colunas: [
      { campo: "nome", rotulo: "Zona" },
      { campo: "tipo", rotulo: "Tipo" },
      { campo: "latitude", rotulo: "Latitude", tipo: "numero" },
      { campo: "longitude", rotulo: "Longitude", tipo: "numero" },
      { campo: "raioMetros", rotulo: "Raio (m)", tipo: "numero" },
      { campo: "responsavel", rotulo: "Responsável" },
    ],
    campos: [
      { campo: "nome", rotulo: "Nome da zona", tipo: "texto", obrigatorio: true },
      { campo: "tipo", rotulo: "Tipo", tipo: "select", opcoes: OPCOES.tipoZona, obrigatorio: true },
      { campo: "cor", rotulo: "Cor no mapa", tipo: "cor" },
      { campo: "latitude", rotulo: "Latitude", tipo: "numero" },
      { campo: "longitude", rotulo: "Longitude", tipo: "numero" },
      { campo: "raioMetros", rotulo: "Raio (metros)", tipo: "numero" },
      { campo: "responsavel", rotulo: "Responsável", tipo: "texto" },
      { campo: "observacoes", rotulo: "Observações", tipo: "textarea", largura: "cheia" },
    ],
  },

  /* ------------------------------------------------------------ ADMINISTRATIVO */
  {
    chave: "efetivo",
    rota: "/central/efetivo",
    titulo: "Gestão do Efetivo",
    curto: "Efetivo",
    singular: "agente",
    descricao: "Cadastro dos agentes da Guarda Civil Municipal.",
    icone: Users,
    secao: "Administrativo",
    ordenarPor: "nome",
    filtros: ["status", "cargo", "setor"],
    colunas: [
      { campo: "matricula", rotulo: "Matrícula" },
      { campo: "nome", rotulo: "Nome" },
      { campo: "nomeGuerra", rotulo: "Nome de guerra" },
      { campo: "cargo", rotulo: "Cargo" },
      { campo: "setor", rotulo: "Setor" },
      { campo: "telefone", rotulo: "Telefone" },
      { campo: "status", rotulo: "Status", tipo: "status" },
    ],
    campos: [
      { campo: "matricula", rotulo: "Matrícula", tipo: "texto", obrigatorio: true },
      { campo: "nome", rotulo: "Nome completo", tipo: "texto", obrigatorio: true },
      { campo: "nomeGuerra", rotulo: "Nome de guerra", tipo: "texto" },
      { campo: "cpf", rotulo: "CPF", tipo: "texto" },
      { campo: "rg", rotulo: "RG", tipo: "texto" },
      { campo: "dataNascimento", rotulo: "Data de nascimento", tipo: "data" },
      { campo: "cargo", rotulo: "Cargo/Graduação", tipo: "select", opcoes: OPCOES.cargo, obrigatorio: true },
      { campo: "setor", rotulo: "Setor", tipo: "select", opcoes: OPCOES.setor, obrigatorio: true },
      { campo: "status", rotulo: "Situação", tipo: "select", opcoes: OPCOES.statusAgente, obrigatorio: true },
      { campo: "telefone", rotulo: "Telefone", tipo: "texto" },
      { campo: "email", rotulo: "E-mail", tipo: "texto" },
      { campo: "dataAdmissao", rotulo: "Data de admissão", tipo: "data" },
      { campo: "endereco", rotulo: "Endereço", tipo: "texto", largura: "cheia" },
      { campo: "qualificacoes", rotulo: "Qualificações", tipo: "textarea", largura: "cheia" },
      { campo: "certificacoes", rotulo: "Certificações/Cursos", tipo: "textarea", largura: "cheia" },
      { campo: "fotoUrl", rotulo: "URL da foto", tipo: "texto", largura: "cheia" },
      { campo: "observacoes", rotulo: "Observações", tipo: "textarea", largura: "cheia" },
    ],
  },
  {
    chave: "escalas",
    rota: "/central/escalas",
    titulo: "Escalas de Serviço",
    curto: "Escalas",
    singular: "escala",
    descricao: "Distribuição do efetivo por turno, função e viatura.",
    icone: CalendarRange,
    secao: "Administrativo",
    ordenarPor: "data",
    filtros: ["status", "tipo", "turno"],
    colunas: [
      { campo: "data", rotulo: "Data", tipo: "data" },
      { campo: "turno", rotulo: "Turno" },
      { campo: "agenteId", rotulo: "Agente", tipo: "relacao", relacao: "efetivo" },
      { campo: "funcao", rotulo: "Função" },
      { campo: "viaturaId", rotulo: "Viatura", tipo: "relacao", relacao: "viaturas" },
      { campo: "tipo", rotulo: "Tipo" },
      { campo: "status", rotulo: "Status", tipo: "status" },
    ],
    campos: [
      { campo: "data", rotulo: "Data", tipo: "data", obrigatorio: true },
      { campo: "turno", rotulo: "Turno", tipo: "select", opcoes: OPCOES.turnoEscala, obrigatorio: true },
      { campo: "tipo", rotulo: "Tipo", tipo: "select", opcoes: OPCOES.tipoEscala, obrigatorio: true },
      { campo: "status", rotulo: "Status", tipo: "select", opcoes: OPCOES.statusEscala, obrigatorio: true },
      { campo: "agenteId", rotulo: "Agente", tipo: "relacao", relacao: "efetivo" },
      { campo: "funcao", rotulo: "Função", tipo: "texto" },
      { campo: "viaturaId", rotulo: "Viatura", tipo: "relacao", relacao: "viaturas" },
      { campo: "setor", rotulo: "Setor", tipo: "texto" },
      { campo: "observacoes", rotulo: "Observações", tipo: "textarea", largura: "cheia" },
    ],
  },
  {
    chave: "viaturas",
    rota: "/central/viaturas",
    titulo: "Controle de Viaturas",
    curto: "Viaturas",
    singular: "viatura",
    descricao: "Frota, situação operacional e manutenções.",
    icone: Car,
    secao: "Administrativo",
    propria: true,
    ordenarPor: "prefixo",
    filtros: ["status", "tipo"],
    colunas: [
      { campo: "prefixo", rotulo: "Prefixo" },
      { campo: "placa", rotulo: "Placa" },
      { campo: "modelo", rotulo: "Modelo" },
      { campo: "tipo", rotulo: "Tipo" },
      { campo: "quilometragem", rotulo: "KM", tipo: "numero" },
      { campo: "proximaManutencao", rotulo: "Próx. manutenção", tipo: "data" },
      { campo: "status", rotulo: "Status", tipo: "status" },
    ],
    campos: [
      { campo: "prefixo", rotulo: "Prefixo", tipo: "texto" },
      { campo: "placa", rotulo: "Placa", tipo: "texto", obrigatorio: true },
      { campo: "modelo", rotulo: "Modelo", tipo: "texto" },
      { campo: "marca", rotulo: "Marca", tipo: "texto" },
      { campo: "ano", rotulo: "Ano", tipo: "numero" },
      { campo: "cor", rotulo: "Cor", tipo: "texto" },
      { campo: "tipo", rotulo: "Tipo", tipo: "select", opcoes: OPCOES.tipoViatura, obrigatorio: true },
      { campo: "status", rotulo: "Situação", tipo: "select", opcoes: OPCOES.statusViatura, obrigatorio: true },
      { campo: "quilometragem", rotulo: "Quilometragem", tipo: "numero" },
      { campo: "combustivel", rotulo: "Combustível", tipo: "texto" },
      { campo: "responsavelId", rotulo: "Responsável", tipo: "relacao", relacao: "efetivo" },
      { campo: "ultimaManutencao", rotulo: "Última manutenção", tipo: "data" },
      { campo: "proximaManutencao", rotulo: "Próxima manutenção", tipo: "data" },
      { campo: "latitude", rotulo: "Latitude", tipo: "numero" },
      { campo: "longitude", rotulo: "Longitude", tipo: "numero" },
      { campo: "equipamentos", rotulo: "Equipamentos", tipo: "textarea", largura: "cheia" },
      { campo: "observacoes", rotulo: "Observações", tipo: "textarea", largura: "cheia" },
    ],
  },
  {
    chave: "orgaos",
    rota: "/central/orgaos",
    titulo: "Órgãos e Entidades",
    curto: "Órgãos/Entidades",
    singular: "órgão",
    descricao: "Rede de contatos institucionais e convênios.",
    icone: Building2,
    secao: "Administrativo",
    ordenarPor: "nome",
    filtros: ["tipo"],
    colunas: [
      { campo: "nome", rotulo: "Órgão" },
      { campo: "tipo", rotulo: "Tipo" },
      { campo: "responsavel", rotulo: "Responsável" },
      { campo: "telefone", rotulo: "Telefone" },
      { campo: "telefoneEmergencia", rotulo: "Emergência" },
      { campo: "email", rotulo: "E-mail" },
    ],
    campos: [
      { campo: "nome", rotulo: "Nome do órgão", tipo: "texto", obrigatorio: true, largura: "cheia" },
      { campo: "tipo", rotulo: "Tipo", tipo: "select", opcoes: OPCOES.tipoOrgao, obrigatorio: true },
      { campo: "responsavel", rotulo: "Responsável", tipo: "texto" },
      { campo: "telefone", rotulo: "Telefone", tipo: "texto" },
      { campo: "telefoneEmergencia", rotulo: "Telefone de emergência", tipo: "texto" },
      { campo: "email", rotulo: "E-mail", tipo: "texto" },
      { campo: "endereco", rotulo: "Endereço", tipo: "texto", largura: "cheia" },
      { campo: "convenio", rotulo: "Convênio/Parceria", tipo: "texto" },
      { campo: "vigenciaConvenio", rotulo: "Vigência do convênio", tipo: "data" },
      { campo: "observacoes", rotulo: "Observações", tipo: "textarea", largura: "cheia" },
    ],
  },

  /* ---------------------------------------------------------------- RELATÓRIOS */
  {
    chave: "relatorios",
    rota: "/central/relatorios",
    titulo: "Relatórios",
    curto: "Relatórios",
    singular: "relatório",
    descricao: "Geração de relatórios por período e exportação em CSV.",
    icone: FileText,
    secao: "Relatórios",
    propria: true,
  },
  {
    chave: "estatisticas",
    rota: "/central/estatisticas",
    titulo: "Estatísticas",
    curto: "Estatísticas",
    descricao: "Análise gráfica da atividade operacional.",
    icone: BarChart3,
    secao: "Relatórios",
    propria: true,
  },
  {
    chave: "indicadores",
    rota: "/central/indicadores",
    titulo: "Indicadores de Desempenho",
    curto: "Indicadores",
    singular: "indicador",
    descricao: "Metas, resultados e indicadores automáticos.",
    icone: Gauge,
    secao: "Relatórios",
    propria: true,
    ordenarPor: "nome",
    filtros: ["categoria", "status"],
    colunas: [
      { campo: "nome", rotulo: "Indicador" },
      { campo: "categoria", rotulo: "Categoria" },
      { campo: "valorAtual", rotulo: "Atual", tipo: "numero" },
      { campo: "meta", rotulo: "Meta", tipo: "numero" },
      { campo: "unidade", rotulo: "Unidade" },
      { campo: "periodicidade", rotulo: "Periodicidade" },
      { campo: "status", rotulo: "Status", tipo: "status" },
    ],
    campos: [
      { campo: "nome", rotulo: "Nome do indicador", tipo: "texto", obrigatorio: true, largura: "cheia" },
      { campo: "categoria", rotulo: "Categoria", tipo: "select", opcoes: OPCOES.categoriaIndicador, obrigatorio: true },
      { campo: "unidade", rotulo: "Unidade", tipo: "texto", obrigatorio: true },
      { campo: "meta", rotulo: "Meta", tipo: "numero" },
      { campo: "valorAtual", rotulo: "Valor atual", tipo: "numero" },
      { campo: "sentido", rotulo: "Sentido", tipo: "select", opcoes: OPCOES.sentido, obrigatorio: true },
      { campo: "periodicidade", rotulo: "Periodicidade", tipo: "select", opcoes: OPCOES.periodicidade, obrigatorio: true },
      { campo: "responsavel", rotulo: "Responsável", tipo: "texto" },
      { campo: "status", rotulo: "Status", tipo: "select", opcoes: OPCOES.ativo, obrigatorio: true },
      { campo: "descricao", rotulo: "Descrição", tipo: "textarea", largura: "cheia" },
    ],
  },

  /* -------------------------------------------------------------------- SISTEMA */
  {
    chave: "usuarios",
    rota: "/central/usuarios",
    titulo: "Usuários e Permissões",
    curto: "Usuários",
    singular: "usuário",
    descricao: "Contas de acesso e nível de permissão por módulo.",
    icone: UserCog,
    secao: "Sistema",
    propria: true,
  },
  {
    chave: "configuracoes",
    rota: "/central/configuracoes",
    titulo: "Configurações do Sistema",
    curto: "Configurações",
    descricao: "Dados da instituição, segurança, backup e personalização.",
    icone: Settings,
    secao: "Sistema",
    propria: true,
  },
  {
    chave: "auditoria",
    rota: "/central/auditoria",
    titulo: "Auditoria e Logs",
    curto: "Auditoria",
    descricao: "Trilha de todas as ações realizadas no sistema.",
    icone: ScrollText,
    secao: "Sistema",
    propria: true,
  },
  {
    chave: "backup",
    rota: "/central/backup",
    titulo: "Backup e Restauração",
    curto: "Backup",
    descricao: "Cópias de segurança do banco de dados.",
    icone: Database,
    secao: "Sistema",
    propria: true,
  },
];

/** Módulo extra (manutenções) — exibido dentro da página de Viaturas. */
export const MANUTENCOES: ModuloDef = {
  chave: "viaturas",
  rpc: "manutencoes",
  rota: "/central/viaturas",
  titulo: "Manutenções da Frota",
  curto: "Manutenções",
  singular: "manutenção",
  descricao: "Histórico de manutenções preventivas e corretivas.",
  icone: Wrench,
  secao: "Administrativo",
  ordenarPor: "data",
  filtros: ["status", "tipo"],
  colunas: [
    { campo: "data", rotulo: "Data", tipo: "data" },
    { campo: "viaturaId", rotulo: "Viatura", tipo: "relacao", relacao: "viaturas" },
    { campo: "tipo", rotulo: "Tipo" },
    { campo: "oficina", rotulo: "Oficina" },
    { campo: "quilometragem", rotulo: "KM", tipo: "numero" },
    { campo: "custo", rotulo: "Custo", tipo: "numero" },
    { campo: "status", rotulo: "Status", tipo: "status" },
  ],
  campos: [
    { campo: "data", rotulo: "Data", tipo: "data", obrigatorio: true },
    { campo: "viaturaId", rotulo: "Viatura", tipo: "relacao", relacao: "viaturas" },
    { campo: "tipo", rotulo: "Tipo", tipo: "select", opcoes: OPCOES.tipoManutencao, obrigatorio: true },
    { campo: "status", rotulo: "Status", tipo: "select", opcoes: OPCOES.statusManutencao, obrigatorio: true },
    { campo: "quilometragem", rotulo: "Quilometragem", tipo: "numero" },
    { campo: "custo", rotulo: "Custo (R$)", tipo: "numero" },
    { campo: "oficina", rotulo: "Oficina", tipo: "texto" },
    { campo: "descricao", rotulo: "Descrição do serviço", tipo: "textarea", largura: "cheia" },
  ],
};

export const ATIVIDADE_ICONE = Activity;

export const SECOES: Secao[] = ["Operacional", "Administrativo", "Relatórios", "Sistema"];

export function moduloPorChave(chave: string): ModuloDef | undefined {
  return MODULOS.find((m) => m.chave === chave);
}
